services:  
  front:
    build: ./front/
    command: /bin/sh -c "cd /front/my-app && npm install && npm start"
    volumes:
      - ./front:/front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true